Remove runtime call
BedrockStreaming/sparktest pull request #6
Opened 2022-10-26 10:55 UTC by fpatin

## Why?
Remove runtime call to `org.apache.spark.sql.Dataset#showString`

## How?
Create an object in package `org.apache.spark.sql` to access `org.apache.spark.sql.Dataset#showString` private method

2022-11-02 10:56 UTC, tbony approved these changes, later dismissed

2023-01-24 08:18 UTC, rinzool requested changes
Thanks @fpatin! :+1: 
Can you just update lib version in `build.sbt` and in `README.md` please?

2023-01-24 09:47 UTC, fpatin commented
Hi @rinzool ,
Your welcome :)
I just push the changes you ask.

2023-01-24 09:48 UTC, rinzool approved these changes

2023-02-01 13:28 UTC, merged

2023-02-01 13:37 UTC, rinzool commented
@fpatin I merged the PR, and deployed `0.3.0` :+1: 
Thanks again for your work!